apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "donweather-ms-georesolve.fullname" . }}-config
  labels:
    {{- include "donweather-ms-georesolve.labels" . | nindent 4 }}
data:
  env: {{ .Values.env.env | quote }}
